variable "region" {
  description = "Name of AWS region"
  default     = "us-east-1"
}

variable "topic_name" {
  description = "Name for the SNS topic.By default generated by Terraform."
  type        = string
}

variable "display_name" {
  description = "Display Name for the SNS topic."
  type        = string
  default     = null
}

variable "kms_master_key_id" {
  description = "KMS Key to encrypt SNS topic"
  type        = string
  default     = "aws/sns"
}

variable "tags" {
  #type        = map(string)
  default     = {}
  description = "tags, which could be used for additional tags"
}

variable "access_type" {
  description = "Access type for SNS topic - publish / subscribe / owner"
  type        = string
  default     = "owner"
}

variable "protocol" {
  description = "Protocol type for SNS Subscription"
  type        = string
  default     = null
}

variable "endpoint" {
  description = "Protocol endpoint for SNS Subscription"
  type        = string
  default     = null

}